---
- name: Populate service facts
  service_facts:

- name: Fail if firewalld is not running
  fail:
    msg: "Firewalld must be installed and running."
  when: "('firewalld.service' not in services) or (services['firewalld.service'].state != 'running')"

- name: Configure zone
  include_tasks: zone.yaml
  with_items: "{{ firewall_zones }}"
  loop_control:
    loop_var: zone
