---
- name: Install packages for services
  package:
    name: "{{ item.package }}"
    state: present
  with_items: "{{ cleanos.services }}"

- name: Enable services
  service:
    name: "{{ item.name }}"
    state: started
    enabled: yes
  with_items: "{{ cleanos.services }}"

