---
- name: Install network-scripts
  package:
    name: network-scripts
    state: present

- name: Install dhcp-client
  package:
    name: dhcp-client
    state: present

- name: Enable network service
  service:
    name: network
    state: started
    enabled: yes

- name: Disable NetworkManager
  service:
    name: NetworkManager
    state: stopped
    enabled: no
  when: "'NetworkManager' in services"

- name: Uninstall NetworkManager
  package:
    name: NetworkManager
    state: absent 
